### ISSUE TITLE
Rewriting URL

### ISSUE THREAD

**Issue by mdjigo** [phpmentors-jp/proxy-url-rewrite-bundle#13]
I wanna rewrite my URL , if i use  htaccess, it takes lot of time
Is it possible to use this bundle to rewrite url like this ?

- Replace all characters with accents to there equivalent without accent : Sample é=>e, à=>a

- Replace all non alphanumeric characters to '-'

- Replace all UpperCase to LowerCase characters

How can i use this bundle to do these rewrites perfectly.
Thank you.

**Comment by iteman** [comment]
This bundle is intended for rewriting URLs as `ProxyPassReverse` directives in Apache, not as the `mod_rewrite` module. But a custom listener appropriate for your problem can be created.
